#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIATWDEARBFHVRWVXLB
      secretKey: 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

application:
  bucket:
    name: photoupload3pillar

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: System123#
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
